### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by gokceneraslan** [cornish/HPASubC#6]
Thanks for the great package! Python 2 will eventually come to [an end](http://www.python3statement.org/), so Python 3 support would be really great!
[py3exiv2 package](https://pypi.python.org/pypi/py3exiv2) provides exiv2 functionality AFAIK. Is there any other dependencies requiring Python 2?

**Comment by cornish** [comment]
Python 3 is on the roadmap as it will solve the current pyexiv2 issue (pyexiv2 is getting harder to source). The only real python 2 dependency is me as I come from a time when python 3 was unsupported by major libraries. :)  That said, I don't have any problem with python 3 (I have written some), but when I start typing, python 2 just comes out on the screen. 

Your note has added some weight to the argument to migrate. I will add it to the issues list and if I get a chance try to release a python 3 version.

**Comment by gokceneraslan** [comment]
With `future` or `six` it's super easy to support both Python 2 and 3. I'm even using `download_images_from_gene_list.py` script from Python 3 right now.

**Comment by cornish** [comment]
All scripts should now be compatible with python 2.7 and python 3.  Let me know if you find this not to be true.  Thanks for the feedback!
